### ISSUE TITLE
Library is not usable on the sandbox environment

### ISSUE THREAD

**Issue by bthaens** [itsme-sdk/itsme-golang#3]
Hello,

The communication url is hardcoded in oidc_spec.go. The value is oidcURL := "https://merchant.itsme.be/oidc/.well-known/openid-configuration"

When developing for the sandbox environment, we would like to change this value to 
https://e2emerchant.itsme.be/oidc/.well-known/openid-configuration

Is it possible to make this a configurable property?

Best regards,
Ben

**Comment by JanDeDobbeleer** [comment]
@bthaens hey Ben, we have that on the roadmap. It's a minor change so we'll see if it's possible to do that still this week.

@RoelandMatthijssens ok if I pick this up?

**Comment by RoelandMatthijssens** [comment]
Ofcourse, go nuts!

**Comment by bthaens** [comment]
Thanks! When will this change have effect in the C# library?
